// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikicjkohcjieudvdhtxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlraWNqa29oY2ppZXVkdmRodHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDYzNDYsImV4cCI6MjA2MDk4MjM0Nn0.Go9vcfPIkbOBfdB7op4GOqFLsoDr-1P_dxUjFaXdFmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);